tasks:
  - name: Setup python requirements
    init: |
      /usr/local/bin/pip install -r requirements.txt
      /usr/local/bin/pip install -U autopep8
vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
image:
  file: .gitpod.dockerfile
