tasks:
  - name: Setup python requirements
    init: |
      pyenv install 3.10.7
      pyenv global 3.10.7
      pip install -r requirements.txt
      pip install -U autopep8

  - name: Setup AWS and docker
    init: |
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      rm -r aws
      rm awscliv2.zip
      aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/e5i3d5s5
vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
