tasks:
  - name: Setup python requirements
    init: |
      pyenv install < .python-version
      pip install -r requirements.txt
vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
