tasks:
  - name: Setup python requirements
    init: |
      pyenv install 3.11
      pyenv global 3.11
      pip install -r requirements.txt
      pip install -U autopep8
vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
