tasks:
  - name: Setup python requirements
    init: |
      pip install -r requirements.txt
vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
image:
  file: .gitpod.dockerfile
